# Generated by Django 2.1.7 on 2019-02-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('pub_day', models.IntegerField()),
                ('pub_month', models.IntegerField()),
                ('pub_year', models.IntegerField()),
                ('day_name', models.CharField(max_length=10)),
                ('num_rows', models.IntegerField()),
                ('num_columns', models.IntegerField()),
                ('num_word', models.IntegerField()),
                ('num_blocks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_block', models.BooleanField()),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_num', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleClues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('across', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.ClueSet')),
                ('down', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.ClueSet')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.ManyToManyField(to='collection.PuzzleCell')),
            ],
        ),
        migrations.AddField(
            model_name='puzzlegrid',
            name='rows',
            field=models.ManyToManyField(to='collection.PuzzleRow'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='clues',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clues_of', to='collection.PuzzleClues'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='grid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid_of', to='collection.PuzzleGrid'),
        ),
        migrations.AddField(
            model_name='clueset',
            name='set',
            field=models.ManyToManyField(to='collection.PuzzleClue'),
        ),
    ]
