# Generated by Django 2.1.7 on 2019-03-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('pub_day', models.IntegerField()),
                ('pub_month', models.IntegerField()),
                ('pub_year', models.IntegerField()),
                ('day_name', models.CharField(max_length=10)),
                ('num_rows', models.IntegerField()),
                ('num_columns', models.IntegerField()),
                ('num_words', models.IntegerField()),
                ('num_blocks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_block', models.BooleanField()),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_num', models.IntegerField()),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_clue', to='collection.AbstractClue')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collection.ClueSet')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleClues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('across', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.ClueSet')),
                ('down', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.ClueSet')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.ManyToManyField(to='collection.PuzzleCell')),
            ],
        ),
        migrations.AddField(
            model_name='puzzlegrid',
            name='rows',
            field=models.ManyToManyField(to='collection.PuzzleRow'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='clues',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clues_of', to='collection.PuzzleClues'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_containing', to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='grid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid_of', to='collection.PuzzleGrid'),
        ),
        migrations.AddField(
            model_name='collection',
            name='puzzles',
            field=models.ManyToManyField(related_name='puzzles_in', to='collection.Puzzle'),
        ),
        migrations.AddField(
            model_name='abstractclue',
            name='puzzles',
            field=models.ManyToManyField(blank=True, related_name='puzzles_using', to='collection.Puzzle'),
        ),
    ]
