# Generated by Django 2.1.7 on 2019-03-21 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='grid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='collection.PuzzleGrid'),
        ),
    ]
