# Generated by Django 2.1.7 on 2019-03-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190320_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='clues',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='collection.PuzzleClues'),
        ),
    ]
