# Generated by Django 2.1.7 on 2019-03-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_puzzle_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='num_word',
            new_name='num_words',
        ),
    ]
