# Generated by Django 2.1.7 on 2019-03-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190301_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleclue',
            name='answer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
