# Generated by Django 2.1.7 on 2019-03-21 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190320_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleclues',
            name='across',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_across', to='collection.ClueSet'),
        ),
        migrations.AlterField(
            model_name='puzzleclues',
            name='down',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_down', to='collection.ClueSet'),
        ),
    ]
