# Generated by Django 2.1.7 on 2019-03-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20190320_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='clues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_of', to='collection.PuzzleClues'),
        ),
    ]
