# Generated by Django 2.1.7 on 2019-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20190307_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='primary_source',
        ),
    ]
