# Generated by Django 2.1.7 on 2019-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_collection_primary_source'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
